/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_acceuil (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_modifier (void);
GtkWidget* create_liste_des_capteurs (void);
GtkWidget* create_Home (void);
