/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_acceuil (void)
{
  GtkWidget *acceuil;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *image18;
  GtkWidget *image17;
  GtkWidget *label1;
  GtkWidget *button14;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image15;
  GtkWidget *label49;
  GtkWidget *button10_hany;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label10;
  GtkWidget *bmodifier_hany;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label11;
  GtkWidget *button12_hany;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label12;
  GtkWidget *button16_hany;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label48;

  acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (acceuil), _("Acceuil"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (acceuil), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 16, 64);
  gtk_widget_set_size_request (treeview1, 744, 256);

  image18 = create_pixmap (acceuil, "capteur4.png");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed1), image18, 0, 0);
  gtk_widget_set_size_request (image18, 232, 152);

  image17 = create_pixmap (acceuil, "capteur3.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed1), image17, 576, 0);
  gtk_widget_set_size_request (image17, 112, 104);

  label1 = gtk_label_new (_("<span color=\"red\">Gestion des capteurs</span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 72, 8);
  gtk_widget_set_size_request (label1, 584, 56);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed1), button14, 704, 400);
  gtk_widget_set_size_request (button14, 80, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button14), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Quit"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox14), label49, FALSE, FALSE, 0);

  button10_hany = gtk_button_new ();
  gtk_widget_show (button10_hany);
  gtk_fixed_put (GTK_FIXED (fixed1), button10_hany, 16, 336);
  gtk_widget_set_size_request (button10_hany, 144, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button10_hany), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (image2), 0.53, 0.52);

  label10 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox1), label10, FALSE, FALSE, 0);

  bmodifier_hany = gtk_button_new ();
  gtk_widget_show (bmodifier_hany);
  gtk_fixed_put (GTK_FIXED (fixed1), bmodifier_hany, 192, 336);
  gtk_widget_set_size_request (bmodifier_hany, 144, 56);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (bmodifier_hany), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);

  button12_hany = gtk_button_new ();
  gtk_widget_show (button12_hany);
  gtk_fixed_put (GTK_FIXED (fixed1), button12_hany, 368, 336);
  gtk_widget_set_size_request (button12_hany, 144, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button12_hany), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (image4), 0.55, 1);
  gtk_misc_set_padding (GTK_MISC (image4), 8, 9);

  label12 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 0);

  button16_hany = gtk_button_new ();
  gtk_widget_show (button16_hany);
  gtk_fixed_put (GTK_FIXED (fixed1), button16_hany, 536, 336);
  gtk_widget_set_size_request (button16_hany, 144, 56);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button16_hany), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-print-report", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox13), label48, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10_hany, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);
  g_signal_connect ((gpointer) bmodifier_hany, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12_hany, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16_hany, "clicked",
                    G_CALLBACK (on_button16_hany_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuil, acceuil, "acceuil");
  GLADE_HOOKUP_OBJECT (acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (acceuil, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (acceuil, image18, "image18");
  GLADE_HOOKUP_OBJECT (acceuil, image17, "image17");
  GLADE_HOOKUP_OBJECT (acceuil, label1, "label1");
  GLADE_HOOKUP_OBJECT (acceuil, button14, "button14");
  GLADE_HOOKUP_OBJECT (acceuil, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (acceuil, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (acceuil, image15, "image15");
  GLADE_HOOKUP_OBJECT (acceuil, label49, "label49");
  GLADE_HOOKUP_OBJECT (acceuil, button10_hany, "button10_hany");
  GLADE_HOOKUP_OBJECT (acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (acceuil, image2, "image2");
  GLADE_HOOKUP_OBJECT (acceuil, label10, "label10");
  GLADE_HOOKUP_OBJECT (acceuil, bmodifier_hany, "bmodifier_hany");
  GLADE_HOOKUP_OBJECT (acceuil, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (acceuil, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (acceuil, image3, "image3");
  GLADE_HOOKUP_OBJECT (acceuil, label11, "label11");
  GLADE_HOOKUP_OBJECT (acceuil, button12_hany, "button12_hany");
  GLADE_HOOKUP_OBJECT (acceuil, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (acceuil, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (acceuil, image4, "image4");
  GLADE_HOOKUP_OBJECT (acceuil, label12, "label12");
  GLADE_HOOKUP_OBJECT (acceuil, button16_hany, "button16_hany");
  GLADE_HOOKUP_OBJECT (acceuil, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (acceuil, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (acceuil, image14, "image14");
  GLADE_HOOKUP_OBJECT (acceuil, label48, "label48");

  return acceuil;
}

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixed2;
  GtkWidget *stentry4;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *button5;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label43;
  GtkWidget *button3;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label42;
  GtkWidget *label29;
  GtkWidget *stcombobox2;
  GtkWidget *stcombobox1;
  GtkWidget *label24;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label26;
  GtkWidget *label21;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;
  GtkWidget *radiobutton4;
  GtkWidget *label5;
  GtkWidget *label52;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter), _("Ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajouter), fixed2);

  stentry4 = gtk_entry_new ();
  gtk_widget_show (stentry4);
  gtk_fixed_put (GTK_FIXED (fixed2), stentry4, 144, 80);
  gtk_widget_set_size_request (stentry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (stentry4), 8226);

  spinbutton1_adj = gtk_adjustment_new (25, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 208, 208);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (2, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2, 336, 208);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (2000, 2000, 2022, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 472, 208);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  spinbutton9_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton9, 408, 272);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  spinbutton10_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton10, 160, 272);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  label30 = gtk_label_new (_("Jour"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed2), label30, 160, 208);
  gtk_widget_set_size_request (label30, 49, 24);

  label31 = gtk_label_new (_("Mois"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed2), label31, 272, 208);
  gtk_widget_set_size_request (label31, 49, 25);

  label32 = gtk_label_new (_("Annee"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed2), label32, 408, 208);
  gtk_widget_set_size_request (label32, 56, 25);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 448, 456);
  gtk_widget_set_size_request (button5, 96, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button5), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox8), label43, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 192, 400);
  gtk_widget_set_size_request (button3, 200, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button3), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox7), label42, FALSE, FALSE, 0);

  label29 = gtk_label_new (_("<span color=\"blue\">Etage:</span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed2), label29, 304, 320);
  gtk_widget_set_size_request (label29, 56, 32);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  stcombobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (stcombobox2);
  gtk_fixed_put (GTK_FIXED (fixed2), stcombobox2, 368, 320);
  gtk_widget_set_size_request (stcombobox2, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox2), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox2), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox2), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox2), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox2), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox2), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox2), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox2), _("8"));

  stcombobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (stcombobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), stcombobox1, 168, 320);
  gtk_widget_set_size_request (stcombobox1, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox1), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox1), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox1), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox1), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox1), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox1), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox1), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox1), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (stcombobox1), _("9"));

  label24 = gtk_label_new (_("<span color=\"blue\">Zone:</span>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed2), label24, 48, 320);
  gtk_widget_set_size_request (label24, 80, 32);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label22 = gtk_label_new (_("<span color=\"blue\">Valeur Maximale :</span>\n"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed2), label22, 240, 264);
  gtk_widget_set_size_request (label22, 144, 40);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label23 = gtk_label_new (_("<span color=\"blue\">Valeur Minimale :</span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed2), label23, 32, 272);
  gtk_widget_set_size_request (label23, 120, 24);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label26 = gtk_label_new (_("<span color=\"blue\">Date d'achat :</span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed2), label26, 40, 200);
  gtk_widget_set_size_request (label26, 96, 48);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label21 = gtk_label_new (_("<span color=\"blue\">Type:</span>\n"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 32, 152);
  gtk_widget_set_size_request (label21, 88, 32);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 128, 144);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Debit"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 256, 144);
  gtk_widget_set_size_request (radiobutton2, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Fumee"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton3, 328, 144);
  gtk_widget_set_size_request (radiobutton3, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Mouvement"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton4, 408, 144);
  gtk_widget_set_size_request (radiobutton4, 112, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  label5 = gtk_label_new (_("<span color=\"blue\">ID:</span>\n"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 24, 88);
  gtk_widget_set_size_request (label5, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  label52 = gtk_label_new (_("<span color=\"red\">Ajouter un capteur</span>"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed2), label52, 176, 8);
  gtk_widget_set_size_request (label52, 208, 48);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajouter, stentry4, "stentry4");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (ajouter, label30, "label30");
  GLADE_HOOKUP_OBJECT (ajouter, label31, "label31");
  GLADE_HOOKUP_OBJECT (ajouter, label32, "label32");
  GLADE_HOOKUP_OBJECT (ajouter, button5, "button5");
  GLADE_HOOKUP_OBJECT (ajouter, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (ajouter, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (ajouter, image9, "image9");
  GLADE_HOOKUP_OBJECT (ajouter, label43, "label43");
  GLADE_HOOKUP_OBJECT (ajouter, button3, "button3");
  GLADE_HOOKUP_OBJECT (ajouter, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajouter, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajouter, image8, "image8");
  GLADE_HOOKUP_OBJECT (ajouter, label42, "label42");
  GLADE_HOOKUP_OBJECT (ajouter, label29, "label29");
  GLADE_HOOKUP_OBJECT (ajouter, stcombobox2, "stcombobox2");
  GLADE_HOOKUP_OBJECT (ajouter, stcombobox1, "stcombobox1");
  GLADE_HOOKUP_OBJECT (ajouter, label24, "label24");
  GLADE_HOOKUP_OBJECT (ajouter, label22, "label22");
  GLADE_HOOKUP_OBJECT (ajouter, label23, "label23");
  GLADE_HOOKUP_OBJECT (ajouter, label26, "label26");
  GLADE_HOOKUP_OBJECT (ajouter, label21, "label21");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (ajouter, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajouter, label52, "label52");

  return ajouter;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed3;
  GtkWidget *entry6;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkWidget *entrychercher;
  GtkWidget *radiobutton5;
  GSList *radiobutton5_group = NULL;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton7;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *radiobutton8;
  GtkWidget *comboboxentry8;
  GtkWidget *comboboxentry7;
  GtkWidget *button16chercher;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label51;
  GtkWidget *button7;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label45;
  GtkWidget *button6;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label44;
  GtkWidget *label50;
  GtkWidget *label7;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label53;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("Modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier), fixed3);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 136, 112);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton4, 216, 200);
  gtk_widget_set_size_request (spinbutton4, 48, 24);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 12, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton5, 344, 200);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (2000, 0, 2022, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton6, 488, 208);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  spinbutton7_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton7, 176, 256);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  spinbutton8_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton8, 432, 256);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  entrychercher = gtk_entry_new ();
  gtk_widget_show (entrychercher);
  gtk_fixed_put (GTK_FIXED (fixed3), entrychercher, 224, 72);
  gtk_widget_set_size_request (entrychercher, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrychercher), 8226);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Temperature"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton5, 136, 160);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("Debit"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton6, 256, 160);
  gtk_widget_set_size_request (radiobutton6, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("Fum\303\251e"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton7, 352, 160);
  gtk_widget_set_size_request (radiobutton7, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  label39 = gtk_label_new (_("Jour"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed3), label39, 160, 200);
  gtk_widget_set_size_request (label39, 48, 32);

  label40 = gtk_label_new (_("Mois"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed3), label40, 280, 200);
  gtk_widget_set_size_request (label40, 64, 32);

  label41 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed3), label41, 416, 200);
  gtk_widget_set_size_request (label41, 72, 24);

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("Mouvement"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton8, 448, 152);
  gtk_widget_set_size_request (radiobutton8, 120, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  comboboxentry8 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry8);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry8, 400, 312);
  gtk_widget_set_size_request (comboboxentry8, 72, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry8), _("8"));

  comboboxentry7 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry7);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry7, 120, 312);
  gtk_widget_set_size_request (comboboxentry7, 64, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry7), _("9"));

  button16chercher = gtk_button_new ();
  gtk_widget_show (button16chercher);
  gtk_fixed_put (GTK_FIXED (fixed3), button16chercher, 416, 72);
  gtk_widget_set_size_request (button16chercher, 128, 24);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button16chercher), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox15), label51, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 488, 408);
  gtk_widget_set_size_request (button7, 96, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button7), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox10), label45, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed3), button6, 184, 360);
  gtk_widget_set_size_request (button6, 192, 48);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button6), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox9), label44, FALSE, FALSE, 0);

  label50 = gtk_label_new (_("<span color=\"blue\">Recherche de capteurs par ID :</span>"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed3), label50, 0, 72);
  gtk_widget_set_size_request (label50, 224, 24);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  label7 = gtk_label_new (_("<span color=\"blue\">ID :</span>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 16, 104);
  gtk_widget_set_size_request (label7, 152, 40);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  label33 = gtk_label_new (_("<span color=\"blue\">Type :</span>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed3), label33, 56, 160);
  gtk_widget_set_size_request (label33, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label34 = gtk_label_new (_("<span color=\"blue\">Date d'achat :</span>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed3), label34, 32, 208);
  gtk_widget_set_size_request (label34, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  label35 = gtk_label_new (_("<span color=\"blue\">Valeur Minimale :</span>"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed3), label35, 16, 256);
  gtk_widget_set_size_request (label35, 144, 24);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  label36 = gtk_label_new (_("<span color=\"blue\">Valeur Maximale :</span>"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed3), label36, 288, 256);
  gtk_widget_set_size_request (label36, 128, 24);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  label37 = gtk_label_new (_("<span color=\"blue\">Zone :</span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed3), label37, 40, 312);
  gtk_widget_set_size_request (label37, 80, 32);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  label38 = gtk_label_new (_("<span color=\"blue\">Etage :</span>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed3), label38, 280, 312);
  gtk_widget_set_size_request (label38, 96, 32);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label53 = gtk_label_new (_("<span color=\"red\">Modification des capteurs</span>"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed3), label53, 120, 16);
  gtk_widget_set_size_request (label53, 296, 40);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  g_signal_connect ((gpointer) radiobutton5, "toggled",
                    G_CALLBACK (on_radiobutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6, "toggled",
                    G_CALLBACK (on_radiobutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (on_radiobutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton8, "toggled",
                    G_CALLBACK (on_radiobutton8_toggled),
                    NULL);
  g_signal_connect ((gpointer) button16chercher, "clicked",
                    G_CALLBACK (on_button16chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (modifier, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (modifier, entrychercher, "entrychercher");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (modifier, label39, "label39");
  GLADE_HOOKUP_OBJECT (modifier, label40, "label40");
  GLADE_HOOKUP_OBJECT (modifier, label41, "label41");
  GLADE_HOOKUP_OBJECT (modifier, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (modifier, comboboxentry8, "comboboxentry8");
  GLADE_HOOKUP_OBJECT (modifier, comboboxentry7, "comboboxentry7");
  GLADE_HOOKUP_OBJECT (modifier, button16chercher, "button16chercher");
  GLADE_HOOKUP_OBJECT (modifier, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (modifier, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (modifier, image16, "image16");
  GLADE_HOOKUP_OBJECT (modifier, label51, "label51");
  GLADE_HOOKUP_OBJECT (modifier, button7, "button7");
  GLADE_HOOKUP_OBJECT (modifier, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (modifier, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (modifier, image11, "image11");
  GLADE_HOOKUP_OBJECT (modifier, label45, "label45");
  GLADE_HOOKUP_OBJECT (modifier, button6, "button6");
  GLADE_HOOKUP_OBJECT (modifier, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifier, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier, image10, "image10");
  GLADE_HOOKUP_OBJECT (modifier, label44, "label44");
  GLADE_HOOKUP_OBJECT (modifier, label50, "label50");
  GLADE_HOOKUP_OBJECT (modifier, label7, "label7");
  GLADE_HOOKUP_OBJECT (modifier, label33, "label33");
  GLADE_HOOKUP_OBJECT (modifier, label34, "label34");
  GLADE_HOOKUP_OBJECT (modifier, label35, "label35");
  GLADE_HOOKUP_OBJECT (modifier, label36, "label36");
  GLADE_HOOKUP_OBJECT (modifier, label37, "label37");
  GLADE_HOOKUP_OBJECT (modifier, label38, "label38");
  GLADE_HOOKUP_OBJECT (modifier, label53, "label53");

  return modifier;
}

GtkWidget*
create_liste_des_capteurs (void)
{
  GtkWidget *liste_des_capteurs;
  GtkWidget *fixed5;
  GtkWidget *def_treeview;
  GtkWidget *button15_retour;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image24;
  GtkWidget *label61;
  GtkWidget *label55;
  GtkWidget *def_aff;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image19;
  GtkWidget *label54;

  liste_des_capteurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (liste_des_capteurs), _("Liste des capteurs d\303\251fectueux"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (liste_des_capteurs), fixed5);

  def_treeview = gtk_tree_view_new ();
  gtk_widget_show (def_treeview);
  gtk_fixed_put (GTK_FIXED (fixed5), def_treeview, 24, 48);
  gtk_widget_set_size_request (def_treeview, 464, 248);

  button15_retour = gtk_button_new ();
  gtk_widget_show (button15_retour);
  gtk_fixed_put (GTK_FIXED (fixed5), button15_retour, 440, 352);
  gtk_widget_set_size_request (button15_retour, 74, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button15_retour), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image24 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox20), image24, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox20), label61, FALSE, FALSE, 0);

  label55 = gtk_label_new (_("<span color=\"red\">Liste des capteurs d\303\251fectueux</span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed5), label55, 120, 0);
  gtk_widget_set_size_request (label55, 304, 48);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  def_aff = gtk_button_new ();
  gtk_widget_show (def_aff);
  gtk_fixed_put (GTK_FIXED (fixed5), def_aff, 208, 312);
  gtk_widget_set_size_request (def_aff, 128, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (def_aff), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image19 = gtk_image_new_from_stock ("gtk-select-all", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox16), image19, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox16), label54, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button15_retour, "clicked",
                    G_CALLBACK (on_button15_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) def_aff, "clicked",
                    G_CALLBACK (on_def_aff_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (liste_des_capteurs, liste_des_capteurs, "liste_des_capteurs");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, def_treeview, "def_treeview");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, button15_retour, "button15_retour");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, image24, "image24");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, label61, "label61");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, label55, "label55");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, def_aff, "def_aff");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, image19, "image19");
  GLADE_HOOKUP_OBJECT (liste_des_capteurs, label54, "label54");

  return liste_des_capteurs;
}

GtkWidget*
create_Home (void)
{
  GtkWidget *Home;
  GtkWidget *fixed6;
  GtkWidget *buttonhome_acceuil;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image21;
  GtkWidget *label57;
  GtkWidget *button_capteur_def;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image22;
  GtkWidget *label58;
  GtkWidget *buttonhome_exit;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image20;
  GtkWidget *label56;
  GtkWidget *image23;
  GtkWidget *Bienvenue_Technician;
  GtkWidget *label60;

  Home = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Home), _("Home"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Home), fixed6);

  buttonhome_acceuil = gtk_button_new ();
  gtk_widget_show (buttonhome_acceuil);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonhome_acceuil, 0, 408);
  gtk_widget_set_size_request (buttonhome_acceuil, 120, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonhome_acceuil), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image21 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox18), image21, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox18), label57, FALSE, FALSE, 0);

  button_capteur_def = gtk_button_new ();
  gtk_widget_show (button_capteur_def);
  gtk_fixed_put (GTK_FIXED (fixed6), button_capteur_def, 168, 408);
  gtk_widget_set_size_request (button_capteur_def, 240, 48);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_capteur_def), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image22 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox19), image22, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("Capteur D\303\251fectueux"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox19), label58, FALSE, FALSE, 0);

  buttonhome_exit = gtk_button_new ();
  gtk_widget_show (buttonhome_exit);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonhome_exit, 456, 408);
  gtk_widget_set_size_request (buttonhome_exit, 112, 48);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonhome_exit), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image20 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox17), image20, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("Exit"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox17), label56, FALSE, FALSE, 0);

  image23 = create_pixmap (Home, "techh.jpg");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed6), image23, 0, 48);
  gtk_widget_set_size_request (image23, 568, 360);

  Bienvenue_Technician = gtk_label_new ("");
  gtk_widget_show (Bienvenue_Technician);
  gtk_fixed_put (GTK_FIXED (fixed6), Bienvenue_Technician, 168, 16);
  gtk_widget_set_size_request (Bienvenue_Technician, 49, 17);

  label60 = gtk_label_new (_("<span color=\"red\">Bienvenue dans l'esapace de technicien</span>"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed6), label60, 128, 0);
  gtk_widget_set_size_request (label60, 312, 48);
  gtk_label_set_use_markup (GTK_LABEL (label60), TRUE);

  g_signal_connect ((gpointer) buttonhome_acceuil, "clicked",
                    G_CALLBACK (on_buttonhome_acceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_capteur_def, "clicked",
                    G_CALLBACK (on_button_capteur_def_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonhome_exit, "clicked",
                    G_CALLBACK (on_buttonhome_exit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Home, Home, "Home");
  GLADE_HOOKUP_OBJECT (Home, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Home, buttonhome_acceuil, "buttonhome_acceuil");
  GLADE_HOOKUP_OBJECT (Home, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Home, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Home, image21, "image21");
  GLADE_HOOKUP_OBJECT (Home, label57, "label57");
  GLADE_HOOKUP_OBJECT (Home, button_capteur_def, "button_capteur_def");
  GLADE_HOOKUP_OBJECT (Home, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Home, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Home, image22, "image22");
  GLADE_HOOKUP_OBJECT (Home, label58, "label58");
  GLADE_HOOKUP_OBJECT (Home, buttonhome_exit, "buttonhome_exit");
  GLADE_HOOKUP_OBJECT (Home, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Home, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Home, image20, "image20");
  GLADE_HOOKUP_OBJECT (Home, label56, "label56");
  GLADE_HOOKUP_OBJECT (Home, image23, "image23");
  GLADE_HOOKUP_OBJECT (Home, Bienvenue_Technician, "Bienvenue_Technician");
  GLADE_HOOKUP_OBJECT (Home, label60, "label60");

  return Home;
}

