/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_SignIN (void);
GtkWidget* create_AddUser (void);
GtkWidget* create_AdminDashboard (void);
GtkWidget* create_ModifyUser (void);
GtkWidget* create_DeleteUserPopup (void);
GtkWidget* create_Alarmes (void);
GtkWidget* create_afiicher_st (void);
GtkWidget* create_ajouter_st (void);
GtkWidget* create_modifier_st (void);
GtkWidget* create_supprimer_st (void);
GtkWidget* create_tache2 (void);
GtkWidget* create_Acceuil_stock (void);
GtkWidget* create_acceuil (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_modifier (void);
GtkWidget* create_liste_des_capteurs (void);
GtkWidget* create_Home (void);
GtkWidget* create_bienvenue (void);
GtkWidget* create_modifier_menu_hsm (void);
GtkWidget* create_ajoutermenu (void);
GtkWidget* create_affichermenu (void);
GtkWidget* create_meilleur_menu_hsm (void);
GtkWidget* create_home_in (void);
GtkWidget* create_afficher_et (void);
GtkWidget* create_ajouter_et (void);
GtkWidget* create_Modifier_et (void);
GtkWidget* create_supprimer_et (void);
GtkWidget* create_tache22 (void);
GtkWidget* create_accuile_et (void);
